### ISSUE TITLE
Roles in shift set showing as "Shift Unavailable" despite the shift set being set to Enabled.

### ISSUE THREAD

**Issue by monikersupreme** [BurningFlipside/VolunteerSystem#125]
I am currently running into an issue with a shift set I've created (Tues TEST Shift) for Ice. I need to be able to assign the Camp Contact and create a group link for the rest of the shift set, however, the Camp Contact role is showing as "Shift Unavailable" despite the shift set being Enabled. There are no pending approvals showing up for this role and the other roles appear to be assignable. Deleting and recreating the shift set does not seem to remedy this issue. 

![image](https://user-images.githubusercontent.com/3332990/160986050-f276d347-9721-4bb8-afb9-f36a21101d21.png)

![image](https://user-images.githubusercontent.com/3332990/160985916-b99c6870-ee39-4f8e-9a07-db49d30b1399.png)

**Comment by pboyd04** [comment]
You made the role private. The reason the other private roles are showing is that you didn't click into the email list box so that never got set for them. But the Camp Contact role has an empty email list and show will show up as invite only for everyone. Either make the role public or enter an email list for it and it will work.

**Comment by pboyd04** [comment]
Not public = private. If you click into the restricted to emails and type anything at all the other roles would behave the same. They are available because they were public and you flagged them as private without taking that step, roles that are created as private from the start will have the list populated with empty value
