### ISSUE TITLE
Camp Contact role not appearing in group link sign-up

### ISSUE THREAD

**Issue by monikersupreme** [BurningFlipside/VolunteerSystem#133]
From my admin view:

![image](https://user-images.githubusercontent.com/3332990/163066921-f3c1b24e-729f-4922-90d3-0987ba11fd7b.png)

If I follow the group sign-up link from a separate account (allbread): 

https://secure.burningflipside.com/fvs/groupSignup.php?id=3cd276e7-7645-4afa-a03c-c8dcd216b8e6 

![image](https://user-images.githubusercontent.com/3332990/163066999-b845349c-aa52-471a-ac85-902211ab505d.png)

You mentioned before that there was something special in the way the Camp Contact role had been created but since the role is included in a bunch of the shift-sets I've established I can't remove it. Currently the role is both Public and Group enabled.

**Comment by pboyd04** [comment]
I think you said that you had previously signed up for these shifts to get the group and then abandoned them? That puts the shift back into the general shift pool and doesn't leave it in the group anymore. Again, this is expected behavior. The new button I have you to generate group links will not have this problem.
