### ISSUE TITLE
Can't get reports on past events

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#143]
Would be useful when setting expectations for future events.

**Comment by pboyd04** [comment]
Which report can't you get? I just went through all of them and verified they worked for past events (there is one you need to check show past events before it lets you and that might become more common as we end up with more events)

**Comment by adamjrice** [comment]
Unable to get Shift Statistics at all for past events. Seems like past stats would be especially useful.

Looking at Early Entry/Late Stay, I am able to choose reports, but the actual data is inaccurate. Likewise for Participants without Shifts.

Trying to get Volunteers without Tickets for Flipside 2022, the system chews for a while and throws back "Unable to get ticket status data!"

Trying to produce an old shift schedule, I get the following error:

````
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/common/vendor/slim/slim/Slim/Http/Request.php on line 1019
````

Empty Shifts for Flipside 2022 seems to produce inaccurate data.

This is in the Chromium browser, fwiw.

**Comment by pboyd04** [comment]
Ok fixed early/entry & late stay. Couldn't find any issues with "Participants without shifts" though I would note that Edie has 2 accounts and Sodium didn't actually sign up for any shifts despite doing several. So it's inaccurate, but only because people didn't fully use the system last time. 

And yeah Ticket status for past events won't work. I could write a lot more code to link that up and make it work if you think there is something important there?

The empty shifts report is accurate, but was including pending shifts. I've added a checkbox to let you turn that behavior on and off.

I've fixed the deprecated warning.
