### ISSUE TITLE
Additional fields for shift creation

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#58]
- Role description: Give people a better idea of what they're signing up for. If we're smart, we can populate the "organization" page on our website based on this info
- Credentials: Checkbox to enable, text field to describe
- Experience: similar to credentials
- Early/late windows should be separated or multiple-check combobox because some people are both
- "Shift name"--I assume this is like day/swing/grave, but some descriptive text would help.

If you want to get fancy, include a natural-language parser for dates, which are going to be the biggest PITA to enter. If not, suggest using date-picker fields, and give explicit logic for creating multiple shifts such as "create X versions of this shift every Y [days|hours]."

**Comment by pboyd04** [comment]
- Role description is on the role
- Credentials - If I understand correctly this will also be on role
- Experience - Same
- Early/late - What single shift gives both early arrival and stay late? Wouldn't that be two shifts?
- The shift name is any text the lead wants to give it so that the title is Role: start time to end time

this sounds like a great stretch goal :)

**Comment by adamjrice** [comment]
Yeah, I was conflating shifts and departments, or shifts and roles.

Bog-standard HTML5 does let you specify a field as being a date, and UAs should give you appropriate date-editing tools.

**Comment by pboyd04** [comment]
The start and end time fields are already date fields. I was more talking about the "create X versions of this shift every Y [days|hours]." bit being a stretch goal.
